//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetail
    {
        [DisplayName("Order")]
        public Nullable<int> orderId { get; set; }
        [DisplayName("Ticket")]
        public int ticketId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
