//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFunction
    {
        public int userId { get; set; }
        public int functionId { get; set; }
        public Nullable<int> groupId { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
